context = """
The prehistory of Mexico stretches back millennia. The earliest human artifacts in Mexico are chips of stone tools found near campfire remains in the Valley of Mexico and radiocarbon-dated to circa 10,000 years ago. Mexico is the site of the domestication of maize, tomato, and beans, which produced an agricultural surplus. This enabled the transition from paleo-Indian hunter-gatherers to sedentary agricultural villages beginning around 5000 BCE. In the subsequent formative eras, maize cultivation and cultural traits such as a mythological and religious complex, and a vigesimal (base 20) numeric system, were diffused from the Mexican cultures to the rest of the Mesoamerican culture area. In this period, villages became more dense in terms of population, becoming socially stratified with an artisan class, and developing into chiefdoms. The most powerful rulers had religious and political power, organizing the construction of large ceremonial centers.

The earliest complex civilization in Mexico was the Olmec culture, which flourished on the Gulf Coast from around 1500 BCE. Olmec cultural traits diffused through Mexico into other formative-era cultures in Chiapas, Oaxaca and the Valley of Mexico. The formative period saw the spread of distinct religious and symbolic traditions, as well as artistic and architectural complexes. The formative-era of Mesoamerica is considered one of the six independent cradles of civilization. In the subsequent pre-classical period, the Maya and Zapotec civilizations developed complex centers at Calakmul and Monte Albán, respectively. During this period the first true Mesoamerican writing systems were developed in the Epi-Olmec and the Zapotec cultures. The Mesoamerican writing tradition reached its height in the Classic Maya Hieroglyphic script. The earliest written histories date from this era. The tradition of writing was important after the Spanish conquest in 1521, with indigenous scribes learning to write their languages in alphabetic letters, while also continuing to create pictorial texts.

In Central Mexico, the height of the classic period saw the ascendancy of Teotihuacán, which formed a military and commercial empire whose political influence stretched south into the Maya area as well as north. Teotihuacan, with a population of more than 150,000 people, had some of the largest pyramidal structures in the pre-Columbian Americas. After the collapse of Teotihuacán around 600 AD, competition ensued between several important political centers in central Mexico such as Xochicalco and Cholula. At this time, during the Epi-Classic, Nahua peoples began moving south into Mesoamerica from the North, and became politically and culturally dominant in central Mexico, as they displaced speakers of Oto-Manguean languages. During the early post-classic era (ca. 1000–1519 CE), Central Mexico was dominated by the Toltec culture, Oaxaca by the Mixtec, and the lowland Maya area had important centers at Chichén Itzá and Mayapán. Toward the end of the post-Classic period, the Mexica established dominance, establishing a political and economic empire based in the city of Tenochtitlan (modern Mexico City), extending from central Mexico to the border with Guatemala.Alexander von Humboldt popularized the modern usage of "Aztec" as a collective term applied to all the people linked by trade, custom, religion, and language to the Mexica state and Ēxcān Tlahtōlōyān, the Triple Alliance. In 1843, with the publication of the work of William H. Prescott, it was adopted by most of the world, including 19th-century Mexican scholars who considered it a way to distinguish present-day Mexicans from pre-conquest Mexicans. This usage has been the subject of debate since the late 20th century.

The Aztec empire was an informal or hegemonic empire because it did not exert supreme authority over the conquered territories; it was satisfied with the payment of tributes from them. It was a discontinuous empire because not all dominated territories were connected; for example, the southern peripheral zones of Xoconochco were not in direct contact with the center. The hegemonic nature of the Aztec empire was demonstrated by their restoration of local rulers to their former position after their city-state was conquered. The Aztec did not interfere in local affairs, as long as the tributes were paid. The Aztec of Central Mexico built a tributary empire covering most of central Mexico. The Aztec were noted for practicing human sacrifice on a large scale. Along with this practice, they avoided killing enemies on the battlefield. Their warring casualty rate was far lower than that of their Spanish counterparts, whose principal objective was immediate slaughter during battle. This distinct Mesoamerican cultural tradition of human sacrifice ended with the gradually Spanish conquest in the 16th century. Other Mexican indigenous cultures were conquered and gradually subjected to Spanish colonial rule.

Since the colonial era and through to the twenty-first century, the indigenous roots of Mexican history and culture are essential to Mexican identity. The National Museum of Anthrology in Mexico City is the showcase of the nation's prehispanic glories. Historian Enrique Florescano calls it "a national treasure and a symbol of identity. The museum is the synthesis of an ideological, scientific, and political feat." Mexican Nobel laureate Octavio Paz said of the museum that the "exaltation and glorification of Mexico-Tenochtitlan transforms the Museum of Anthropology into a temple." Mexico pursued international recognition of its prehispanic heritage, and has a large number of UNESCO World Heritage Sites, the largest in the hemisphere. The existence of high indigenous civilization prior to the arrival of Europeans has also had an impact on European thought.

In 2000, after 71 years, the PRI lost a presidential election to Vicente Fox of the opposition conservative National Action Party (PAN). In the 2006 presidential election, Felipe Calderón from the PAN was declared the winner, with a very narrow margin (0.58%) over leftist politician Andrés Manuel López Obrador then the candidate of the Party of the Democratic Revolution (PRD). López Obrador, however, contested the election and pledged to create an "alternative government".

After twelve years, in 2012, the PRI won the presidency again with the election of Enrique Peña Nieto, the governor of the State of Mexico from 2005 to 2011. However, he won with a plurality of about 38%, and did not have a legislative majority.

After founding the new political party MORENA, Andrés Manuel López Obrador won the 2018 presidential election with over 50% of the vote. His political coalition, led by his left-wing party founded after the 2012 elections, includes parties and politicians from all over the political spectrum. The coalition also won a majority in both the upper and lower congress chambers. AMLO's (one of his many nicknames) success is attributed to the country's other strong political alternatives exhausting their chances as well as the politician adopting a moderate discourse with focus on conciliation.

Mexico has contended with high crime rates, official corruption, narcotrafficking, and a stagnant economy. Many state-owned industrial enterprises were privatized starting in the 1990s, with neoliberal reforms, but Pemex, the state-owned petroleum company is only slowly being privatized, with exploration licenses being issued. In AMLO's push against government corruption, the ex-CEO of Pemex has been arrested.

Although there were fears of electoral fraud in Mexico's 2018 presidential elections,[140] the results gave a mandate to AMLO. On 1 December 2018, Andrés Manuel López Obrador was sworn in as the new President of Mexico. After winning a landslide victory in the July 2018 presidential elections, he became the first leftwing president for decades. In June 2021 midterm elections, López Obrador's left-leaning Morena’s coalition lost seats in the lower house of Congress. However, his ruling coalition maintained a simple majority, but López Obrador failed to secure the two-thirds congressional supermajority. The main opposition was a coalition of Mexico's three traditional parties: the center-right Revolutionary Institutional Party, right-wing National Action Party and leftist Party of the Democratic Revolution.

Mexico is located between latitudes 14° and 33°N, and longitudes 86° and 119°W in the southern portion of North America. Almost all of Mexico lies in the North American Plate, with small parts of the Baja California peninsula on the Pacific and Cocos Plates. Geophysically, some geographers include the territory east of the Isthmus of Tehuantepec (around 12% of the total) within Central America. Geopolitically, however, Mexico is entirely considered part of North America, along with Canada and the United States.

Mexico's total area is 1,972,550 km2 (761,606 sq mi), making it the world's 13th largest country by total area. It has coastlines on the Pacific Ocean and Gulf of California, as well as the Gulf of Mexico and Caribbean Sea, the latter two forming part of the Atlantic Ocean. Within these seas are about 6,000 km2 (2,317 sq mi) of islands (including the remote Pacific Guadalupe Island and the Revillagigedo Islands). From its farthest land points, Mexico is a little over 2,000 mi (3,219 km) in length. Mexico has nine distinct regions: Baja California, the Pacific Coastal Lowlands, the Mexican Plateau, the Sierra Madre Oriental, the Sierra Madre Occidental, the Cordillera Neo-Volcánica, the Gulf Coastal Plain, the Southern Highlands, and the Yucatán Peninsula. Although Mexico is large, much of its land mass is incompatible with agriculture due to aridity, soil, or terrain. In 2018, an estimated 54.9% of land is agricultural; 11.8% is arable; 1.4% is in permanent crops; 41.7% is permanent pasture; and 33.3% is forest.

Mexico is crossed from north to south by two mountain ranges known as Sierra Madre Oriental and Sierra Madre Occidental, which are the extension of the Rocky Mountains from northern North America. From east to west at the center, the country is crossed by the Trans-Mexican Volcanic Belt also known as the Sierra Nevada. A fourth mountain range, the Sierra Madre del Sur, runs from Michoacán to Oaxaca. As such, the majority of the Mexican central and northern territories are located at high altitudes, and the highest elevations are found at the Trans-Mexican Volcanic Belt: Pico de Orizaba (5,700 m or 18,701 ft), Popocatépetl (5,462 m or 17,920 ft) and Iztaccihuatl (5,286 m or 17,343 ft) and the Nevado de Toluca (4,577 m or 15,016 ft). Three major urban agglomerations are located in the valleys between these four elevations: Toluca, Greater Mexico City and Puebla.[citation needed] An important geologic feature of the Yucatán peninsula is the Chicxulub crater. The scientific consensus is that the Chicxulub impactor was responsible for the Cretaceous–Paleogene extinction event. Mexico is subject to a number of natural hazards, including hurricanes on both coasts, tsunamis on the Pacific coast, and volcanism.

Mexico has few rivers and lakes. The Lerma River flows west to form Lake Chapala, the country’s largest natural lake. The Santiago River flows from Lake Chapala out of the lake to the Pacific Ocean. The Pánuco River flows to the Gulf of Mexico. Lake Pátzcuaro and Lake Cuitzeo, west of Mexico City, are remnants of vast lakes and marshes that covered much of the southern Mesa Central before European settlement. The central lake system where the Aztec capital of Tenochtitlan and surrounding communities thrived before the Spanish conquest have almost entirely been drained. There are few permanent streams in the arid Mesa del Norte, and most of these drain into the interior rather than to the ocean. By far the most important river in that part of the country is the Río Bravo del Norte (called the Rio Grande in the United States), which forms a lengthy part of the international border from Ciudad Juárez to the Gulf Coast, 3,141 km (1,952 mi). The Balsas River provides hydroelectric power. Grijalva river and Usumacinta river system drains most of the humid Chiapas Highlands. The Papaloapan River flows into the Gulf of Mexico south of Veracruz, the Grijalva and Usumacinta further southeast are significant Mexican rivers. Both the Baja California Peninsula and the Yucatán Peninsula are extremely arid with no surface streams.

The climate of Mexico is quite varied due to the country's size and topography. Tropic of Cancer effectively divides the country into temperate and tropical zones. Land north of the Tropic of Cancer experiences cooler temperatures during the winter months. South of the Tropic of Cancer, temperatures are fairly constant year-round and vary solely as a function of elevation. This gives Mexico one of the world's most diverse weather systems. Maritime air masses bring seasonal precipitation from May until August. Many parts of Mexico, particularly the north, have a dry climate with only sporadic rainfall, while parts of the tropical lowlands in the south average more than 2,000 mm (78.7 in) of annual precipitation. For example, many cities in the north like Monterrey, Hermosillo, and Mexicali experience temperatures of 40 °C (104 °F) or more in summer. In the Sonoran Desert temperatures reach 50 °C (122 °F) or more.

Descriptors of regions are by temperature, with the tierra caliente (hot land) being coastal up to 900 meters; tierra templada (temperate land) being from 1,800 meters; tierra fría (cold land) extending to 3,500 meters. Beyond the cold lands are the páramos, alpine pastures, and the tierra helada (frozen land) (4,000-4,200 meters) in central Mexico. Areas south of the Tropic of Cancer with elevations up to 1,000 m (3,281 ft) (the southern parts of both coastal plains as well as the Yucatán Peninsula), have a yearly median temperature between 24 to 28 °C (75.2 to 82.4 °F). Temperatures here remain high throughout the year, with only a 5 °C (9 °F) difference between winter and summer median temperatures. Both Mexican coasts, except for the south coast of the Bay of Campeche and northern Baja California, are also vulnerable to serious hurricanes during the summer and fall. Although low-lying areas north of the Tropic of Cancer are hot and humid during the summer, they generally have lower yearly temperature averages (from 20 to 24 °C or 68.0 to 75.2 °F) because of more moderate conditions during the winter.

The climate of Mexico is quite varied due to the country's size and topography. Tropic of Cancer effectively divides the country into temperate and tropical zones. Land north of the Tropic of Cancer experiences cooler temperatures during the winter months. South of the Tropic of Cancer, temperatures are fairly constant year-round and vary solely as a function of elevation. This gives Mexico one of the world's most diverse weather systems. Maritime air masses bring seasonal precipitation from May until August. Many parts of Mexico, particularly the north, have a dry climate with only sporadic rainfall, while parts of the tropical lowlands in the south average more than 2,000 mm (78.7 in) of annual precipitation. For example, many cities in the north like Monterrey, Hermosillo, and Mexicali experience temperatures of 40 °C (104 °F) or more in summer. In the Sonoran Desert temperatures reach 50 °C (122 °F) or more.

Descriptors of regions are by temperature, with the tierra caliente (hot land) being coastal up to 900 meters; tierra templada (temperate land) being from 1,800 meters; tierra fría (cold land) extending to 3,500 meters. Beyond the cold lands are the páramos, alpine pastures, and the tierra helada (frozen land) (4,000-4,200 meters) in central Mexico. Areas south of the Tropic of Cancer with elevations up to 1,000 m (3,281 ft) (the southern parts of both coastal plains as well as the Yucatán Peninsula), have a yearly median temperature between 24 to 28 °C (75.2 to 82.4 °F). Temperatures here remain high throughout the year, with only a 5 °C (9 °F) difference between winter and summer median temperatures. Both Mexican coasts, except for the south coast of the Bay of Campeche and northern Baja California, are also vulnerable to serious hurricanes during the summer and fall. Although low-lying areas north of the Tropic of Cancer are hot and humid during the summer, they generally have lower yearly temperature averages (from 20 to 24 °C or 68.0 to 75.2 °F) because of more moderate conditions during the winter.

Three parties have historically been the dominant parties in Mexican politics: the Institutional Revolutionary Party (PRI), a catch-all party and member of the Socialist International that was founded in 1929 to unite all the factions of the Mexican Revolution and held an almost hegemonic power in Mexican politics since then; the National Action Party (PAN), a conservative party founded in 1939 and belonging to the Christian Democrat Organization of America; and the Party of the Democratic Revolution (PRD) a left-wing party,[ founded in 1989 as the successor of the coalition of socialists and liberal parties. PRD emerged after what has now been proven was a stolen election in 1988, and has won numerous state and local elections since then. PAN won its first governorship in 1989, and won the presidency in 2000 and 2006.[173] A new political party, National Regeneration Movement (MORENA), a leftist-populist party, emerged after the 2012 election and dominated the 2018 Mexican general election. Unlike many Latin American countries, the military in Mexico does not participate in politics and is under civilian control, the result of the concerted effort of revolutionary generals who became presidents of Mexico (1920–40) to remove the military from politics.

As Mexico transitioned from one-party rule in 2000, increasingly criminal cartels have attempted to meddle in politics and have an impact on electoral outcomes. Cartels have moved from bribing or otherwise influencing politicians and now attempt to have their preferred candidates elected. A recent publication based on two decades of analysis of data contends that "electoral competition and partisan conflict were key drivers of the outbreak of Mexico's crime wars, the intensification of violence, and the expansion of war and violence to the spheres of local politics and civil society."

The foreign relations of Mexico are directed by the President of Mexico and managed through the Ministry of Foreign Affairs. The principles of the foreign policy are constitutionally recognized in the Article 89, Section 10, which include: respect for international law and legal equality of states, their sovereignty and independence, trend to non-interventionism in the domestic affairs of other countries, peaceful resolution of conflicts, and promotion of collective security through active participation in international organizations. Since the 1930s, the Estrada Doctrine has served as a crucial complement to these principles.

Mexico is a founding member of several international organizations, most notably the United Nations, the Organization of American States, the Organization of Ibero-American States, the OPANAL and the CELAC. In 2008, Mexico contributed over 40 million dollars to the United Nations regular budget. In addition, it was the only Latin American member of the Organization for Economic Co-operation and Development since it joined in 1994 until Chile gained full membership in 2010.

Mexico is considered a regional power hence its presence in major economic groups such as the G8+5 and the G-20. In addition, since the 1990s Mexico has sought a reform of the United Nations Security Council and its working methods with the support of Canada, Italy, Pakistan and other nine countries, which form a group informally called the Coffee Club.

As of April 2018, Mexico has the 15th largest nominal GDP (US$1.15 trillion)[229] and the 11th largest by purchasing power parity (US$2.45 trillion). GDP annual average growth was 2.9% in 2016 and 2% in 2017. Agriculture has comprised 4% of the economy over the last two decades, while industry contributes 33% (mostly automotive, oil, and electronics) and services (notably financial services and tourism) contribute 63%. Mexico's GDP in PPP per capita was US$18,714.05. The World Bank reported in 2009 that the country's Gross National Income in market exchange rates was the second highest in Latin America, after Brazil at US$1,830.392 billion, which led to the highest income per capita in the region at $15,311. Mexico is now firmly established as an upper middle-income country. After the slowdown of 2001 the country has recovered and has grown 4.2, 3.0 and 4.8 percent in 2004, 2005 and 2006, even though it is considered to be well below Mexico's potential growth.] The International Monetary Fund predicts growth rates of 2.3% and 2.7% for 2018 and 2019, respectively.[229] By 2050, Mexico could potentially become the world's fifth or seventh largest economy.

Although multiple international organizations coincide and classify Mexico as an upper middle income country, or a middle class country Mexico's National Council for the Evaluation of Social Development Policy (CONEVAL), which is the organization in charge to measure the country's poverty reports that a huge percentage of Mexico's population lives in poverty. According to said council, from 2006 to 2010 (year on which the CONEVAL published its first nationwide report of poverty) the portion of Mexicans who live in poverty rose from 18%–19% to 46% (52 million people).However, rather than Mexico's economy crashing, international economists attribute the huge increase in the percentage of population living below the country's poverty line to the CONEVAL using new standards to define it, as now besides people who lives below the economic welfare line, people who lacks at least one "social need" such as complete education, access to healthcare, access to regular food, housing services and goods, social security etc. were considered to be living in poverty (several countries do collect information regarding the persistence of said vulnerabilities on their population, but Mexico is the only one that classifies people lacking one or more of those needs as living below its national poverty line). Said economists do point out that the percentage of people living in poverty according to Mexico's national poverty line is around 40 times higher than the one reported by the World Bank's international poverty line (with said difference being the biggest in the world) and ponder if it would not be better for countries in the situation of Mexico to adopt internationalized standards to measure poverty so the numbers obtained could be used to make accurate international comparisons. According to the OECD's own poverty line (defined as the percentage of a country's population who earns 60% or less of the national median income) 20% of Mexico's population lives in a situation of poverty.
Mexico City, the financial center of Mexico
Mexican Stock Exchange building

Among the OECD countries, Mexico has the second-highest degree of economic disparity between the extremely poor and extremely rich, after Chile – although it has been falling over the last decade, being one of few countries in which this is the case. The bottom ten percent in the income hierarchy disposes of 1.36% of the country's resources, whereas the upper ten percent dispose of almost 36%. The OECD also notes that Mexico's budgeted expenses for poverty alleviation and social development is only about a third of the OECD average. This is also reflected by the fact that infant mortality in Mexico is three times higher than the average among OECD nations whereas its literacy levels are in the median range of OECD nations. Nevertheless, according to Goldman Sachs, by 2050 Mexico will have the 5th largest economy in the world. According to a 2008 UN report the average income in a typical urbanized area of Mexico was $26,654, while the average income in rural areas just miles away was only $8,403. Daily minimum wages are set annually being set at $102.68 Mexican pesos (US$5.40) in 2019. All of the indices of social development for the Mexican Indigenous population are considerably lower than the national average, which is motive of concern for the government.

The electronics industry of Mexico has grown enormously within the last decade. Mexico has the sixth largest electronics industry in the world after China, United States, Japan, South Korea, and Taiwan. Mexico is the second-largest exporter of electronics to the United States where it exported $71.4 billion worth of electronics in 2011. The Mexican electronics industry is dominated by the manufacture and OEM design of televisions, displays, computers, mobile phones, circuit boards, semiconductors, electronic appliances, communications equipment and LCD modules. The Mexican electronics industry grew 20% between 2010 and 2011, up from its constant growth rate of 17% between 2003 and 2009. Currently electronics represent 30% of Mexico's exports.

Mexico produces the most automobiles of any North American nation. The industry produces technologically complex components and engages in some research and development activities. The "Big Three" (General Motors, Ford and Chrysler) have been operating in Mexico since the 1930s, while Volkswagen and Nissan built their plants in the 1960s. In Puebla alone, 70 industrial part-makers cluster around Volkswagen. In the 2010s expansion of the sector was surging. In 2014 alone, more than $10 billion in investment was committed. In September 2016 Kia motors opened a $1 billion factory in Nuevo León, with Audi also opening an assembling plant in Puebla the same year. BMW, Mercedes-Benz and Nissan currently have plants in construction.[256] The domestic car industry is represented by DINA S.A., which has built buses and trucks since 1962, and the new Mastretta company that builds the high-performance Mastretta MXT sports car. In 2006, trade with the United States and Canada accounted for almost 50% of Mexico's exports and 45% of its imports. During the first three quarters of 2010, the United States had a $46.0 billion trade deficit with Mexico. In August 2010 Mexico surpassed France to become the 9th largest holder of US debt. The commercial and financial dependence on the US is a cause for concern.

The remittances from Mexican citizens working in the United States account are significant; after dipping during the after the 2008 Great Recession and again during Covid pandemic in 2021 they are topping other sources of foreign income. Remittances are directed to Mexico by direct links from a U.S. government banking program.

As of 2017, Mexico was the 6th most visited country in the world and had the 15th highest income from tourism in the world which is also the highest in Latin America. The vast majority of tourists come to Mexico from the United States and Canada followed by Europe and Asia. A smaller number also come from other Latin American countries. In the 2017 Travel and Tourism Competitiveness Report, Mexico was ranked 22nd in the world, which was 3rd in the Americas.

The coastlines of Mexico harbor many stretches of beaches that are frequented by sunbathers and other visitors. According to national law, the entirety of the coastlines are under federal ownership, that is, all beaches in the country are public. On the Yucatán peninsula, one of the most popular beach destinations is the resort town of Cancún, especially among university students during spring break. Just offshore is the beach island of Isla Mujeres, and to the east is the Isla Holbox. To the south of Cancun is the coastal strip called Riviera Maya which includes the beach town of Playa del Carmen and the ecological parks of Xcaret and Xel-Há. A day trip to the south of Cancún is the historic port of Tulum. In addition to its beaches, the town of Tulum is notable for its cliff-side Mayan ruins. On the Pacific coast is the notable tourist destination of Acapulco. Once the destination for the rich and famous, the beaches have become crowded and the shores are now home to many multi-story hotels and vendors. Acapulco is home to renowned cliff divers: trained divers who leap from the side of a vertical cliff into the surf below. At the southern tip of the Baja California peninsula is the resort town of Cabo San Lucas, a town noted for its beaches and marlin fishing. Further north along the Sea of Cortés is the Bahía de La Concepción, another beach town known for its sports fishing. Closer to the United States border is the weekend draw of San Felipe, Baja California.
Throughout the 19th century, the population of Mexico had barely doubled. This trend continued during the first two decades of the 20th century, and even in the 1921 census there was a loss of about 1 million inhabitants. The phenomenon can be explained because during the decade from 1910 to 1921 the Mexican Revolution took place. The growth rate increased dramatically between the 1930s and the 1980s, when the country registered growth rates of over 3% (1950–1980). The Mexican population doubled in twenty years, and at that rate it was expected that by 2000 there would be 120 million Mexicans. Life expectancy went from 36 years (in 1895) to 72 years (in the year 2000). According to estimations made by Mexico's National Geography and Statistics Institute, is estimated in 2022 to be 129,150,971 as of 2017 Mexico had 123.5 million inhabitants making it the most populous Spanish-speaking country in the world.

In the early 1960s, around 600,000 Mexicans lived abroad, which increased sevenfold by the 1990s to 4.4 million. At the turn of the 21st century, this figure more than doubled to 9.5 million. As of 2017, it is estimated that 12.9 million Mexicans live abroad, primarily in the United States, which concentrates nearly 98% of the expatriate population.
The majority of Mexicans have settled in states such as California, Texas and Illinois, particularly around the metropolitan areas of Los Angeles, Chicago, Houston and Dallas–Fort Worth. As a result of these major migration flows in recent decades, around 36 million U.S. residents, or 11.2% of the country's population, identified as being of full or partial Mexican ancestry.
The remaining 2% of expatriates have settled in Canada (86,000), primarily in the provinces of Ontario and Quebec, followed by Spain (49,000) and Germany (18,000), both European destinations represent almost two-thirds of the Mexican population living in the continent.] As for Latin America, it is estimated that 69,000 Mexicans live in the region, Guatemala (18,000) being the top destination for expatriates, followed by Bolivia (10,000) and Panama (5,000).
As of 2017, it is estimated that 1.2 million foreigners have settled in Mexico, up from nearly 1 million in 2010 The vast majority of migrants come from the United States (900,000), making Mexico the top destination for U.S. citizens abroad. The second largest group comes from neighboring Guatemala (54,500), followed by Spain (27,600). Other major sources of migration are fellow Latin American countries, which include Colombia (20,600), Argentina (19,200) and Cuba (18,100). Historically, the Lebanese diaspora and the German-born Mennonite migration have left a notorious impact in the country's culture, particularly in its cuisine and traditional music. At the turn of the 21st century, several trends have increased the number of foreigners residing in the country such as the 2008–2014 Spanish financial crisis,increasing gang-related violence in the Northern Triangle of Central America, the ongoing political and economic crisis in Venezuela, and the automotive industry boom led by Japanese and South Korean investment.
Mexican culture reflects the complexity of the country's history through the blending of indigenous cultures and the culture of Spain during Spain's 300-year colonial rule of Mexico. The Porfirian era (el Porfiriato) (1876-1911), was marked by economic progress and peace. After four decades of civil unrest and war, Mexico saw the development of philosophy and the arts, promoted by President Porfirio Díaz himself. Since that time, as accentuated during the Mexican Revolution, cultural identity has had its foundation in the mestizaje, of which the indigenous (i.e. Amerindian) element is the core. In light of the various ethnicities that formed the Mexican people, José Vasconcelos in La Raza Cósmica (The Cosmic Race) (1925) defined Mexico to be the melting pot of all races (thus extending the definition of the mestizo) not only biologically but culturally as well. Other Mexican intellectuals grappled with the idea of Lo Mexicano, which seeks "to discover the national ethos of Mexican culture." Nobel laureate Octavio Paz explores the notion of a Mexican national character in The Labyrinth of Solitude.
The origin of the current Mexican cuisine was established during the Spanish colonial era, a mixture of the foods of Spain with native indigenous ingredients. Foods indigenous to Mexico include corn, pepper vegetables, calabazas, avocados, sweet potato, turkey, many beans, and other fruits and spices. Similarly, some cooking techniques used today are inherited from pre-Columbian peoples, such as the nixtamalization of corn, the cooking of food in ovens at ground level, grinding in molcajete and metate. With the Spaniards came the pork, beef and chicken meats; peppercorn, sugar, milk and all its derivatives, wheat and rice, citrus fruits and another constellation of ingredients that are part of the daily diet of Mexicans.
From this meeting of millennia old two culinary traditions, were born pozole, mole sauce, barbacoa and tamale is in its current forms, the chocolate, a large range of breads, tacos, and the broad repertoire of Mexican street foods. Beverages such as atole, champurrado, milk chocolate and aguas frescas were born; desserts such as acitrón and the full range of crystallized sweets, rompope, cajeta, jericaya and the wide repertoire of delights created in the convents of nuns in all parts of the country.
In 2005, Mexico presented the candidature of its gastronomy for World Heritage Site of UNESCO, the first time a country had presented its gastronomic tradition for this purpose.The result was negative, because the committee did not place the proper emphasis on the importance of corn in Mexican cuisine. On 16 November 2010 Mexican gastronomy was recognized as Intangible cultural heritage by UNESCO. In addition, Daniela Soto-Innes was named the best female chef in the world by The World's Best 50 Restaurants in April 2019.
Organized sport in Mexico largely dates from the late nineteenth century, with only bullfighting having a long history dating to the early colonial era. Once the political turmoil of the early republic was replaced by the stability of the Porfiriato did organized sport become public diversions, with structured and ordered play governed by rules and authorities. Baseball was introduced from the United States and also via Cuba in the 1880s and organized teams were created. After the Mexican Revolution, the government sponsored sports to counter the international image of political turmoil and violence.
The bid to host the 1968 Summer Olympics was to burnish Mexico's stature internationally, with is being the first Latin American country to host the games. The government spent abundantly on sporting facilities and other infrastructure to make the games a success, but those expenditures helped fuel public discontent with the government's lack of spending on social programs.Mexico City hosted the XIX Olympic Games in 1968, making it the first Latin American city to do so.[428] The country has also hosted the FIFA World Cup twice, in 1970 and 1986. Mexico's most popular sport is association football.

El Santo, one of the most iconic Mexican luchadores
The Mexican professional baseball league is named the Liga Mexicana de Beisbol. While usually not as strong as the United States, the Caribbean countries and Japan, Mexico has nonetheless achieved several international baseball titles.
Other sporting activities include Bullfighting, boxing, and Lucha Libre (freestyle professional wrestling). Bullfighting (Spanish: corrida de toros) came to Mexico 500 years ago with the arrival of the Spanish. Despite efforts by animal rights activists to outlaw it, bullfighting remains a popular sport in the country, and almost all large cities have bullrings. Plaza México in Mexico City, which seats 45,000 people, is the largest bullring in the world. Freestyle professional wrestling is a major crowd draw with national promotions such as AAA, CMLL and others.
Mexico is an international power in professional boxing. Thirteen Olympic boxing medals have been won by Mexico.

"""
